// Full end-to-end lab packs (deterministic). Uses TARGET_URL from the environment.
import type { LabFile, LabKind } from "./codepack-types";

function pythonMainPy(beef: boolean): string {
  const browserFn = beef
    ? lines(
        "",
        "def probe_browser() -> dict:",
        "    from . import http_client",
        "    snap = http_client.get(target_url())",
        "    body = (snap.get('body_sample') or '').lower()",
        "    hints = ['beef', 'hook', 'browser', 'xss']",
        "    return {'target': target_url(), 'beef_hints_in_body': [h for h in hints if h in body]}",
        "",
      )
    : "";
  const choices = beef
    ? '"setup", "recon", "sqli", "xss", "cmdi", "secrets", "browser", "full", "report"'
    : '"setup", "recon", "sqli", "xss", "cmdi", "secrets", "full", "report"';
  const browserBranch = beef
    ? lines(
        '    elif args.cmd == "browser":',
        "        print(json.dumps(probe_browser(), indent=2))",
      )
    : "";
  const browserFull = beef ? "        probe_browser()" : "";
  return lines(
    '"""CLI: python -m src.main <setup|recon|sqli|xss|cmdi|secrets|full|report>"""',
    "from __future__ import annotations",
    "import argparse",
    "import json",
    "",
    "from .config import ensure_evidence, target_url",
    "from . import recon, probes, report",
    browserFn.trim() ? browserFn : "",
    "",
    "def main() -> None:",
    "    ap = argparse.ArgumentParser(description='OHQS end-to-end lab runner')",
    "    ap.add_argument('cmd', choices=[" + choices + "])",
    "    args = ap.parse_args()",
    '    if args.cmd == "setup":',
    "        ensure_evidence()",
    '        print(json.dumps({"target": target_url(), "evidence": "ready"}, indent=2))',
    '    elif args.cmd == "recon":',
    "        print(json.dumps(recon.run(), indent=2))",
    '    elif args.cmd == "sqli":',
    "        print(json.dumps(probes.probe_sqli(), indent=2))",
    '    elif args.cmd == "xss":',
    "        print(json.dumps(probes.probe_xss(), indent=2))",
    '    elif args.cmd == "cmdi":',
    "        print(json.dumps(probes.probe_cmdi(), indent=2))",
    '    elif args.cmd == "secrets":',
    "        print(json.dumps(probes.probe_secrets_on_disk(), indent=2))",
    browserBranch,
    '    elif args.cmd == "full":',
    "        ensure_evidence()",
    "        recon.run()",
    "        probes.probe_sqli()",
    "        probes.probe_xss()",
    "        probes.probe_cmdi()",
    "        probes.probe_secrets_on_disk()",
    browserFull,
    "        print(report.render_findings())",
    "    else:",
    "        print(report.render_findings())",
    "",
    "",
    'if __name__ == "__main__":',
    "    main()",
  );
}

function lines(...rows: string[]): string {
  return rows.join("\n") + "\n";
}

function slug(s: string): string {
  return (
    (s || "lab")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "lab"
  );
}

export function pythonE2eFiles(_complexity: number, kind: LabKind): LabFile[] {
  const beef = kind === "browser_beef";
  return [
    {
      path: "requirements.txt",
      content: lines("requests>=2.31.0", "urllib3>=2.0.0"),
    },
    {
      path: "src/__init__.py",
      content: lines('"""OpenHat Quick Start — runnable offsec research lab."""'),
    },
    {
      path: "src/config.py",
      content: lines(
        "from __future__ import annotations",
        "import os",
        "from pathlib import Path",
        "",
        "ROOT = Path(__file__).resolve().parents[1]",
        'EVIDENCE = ROOT / "evidence"',
        "",
        "",
        "def target_url() -> str:",
        '    return os.environ.get("TARGET_URL", "https://lab.example.invalid").strip()',
        "",
        "",
        "def ensure_evidence() -> None:",
        "    EVIDENCE.mkdir(parents=True, exist_ok=True)",
      ),
    },
    {
      path: "src/http_client.py",
      content: lines(
        "from __future__ import annotations",
        "import json",
        "from typing import Any",
        "",
        "import requests",
        "",
        "from .config import EVIDENCE, ensure_evidence",
        "",
        "TIMEOUT = 25",
        "",
        "",
        "def session() -> requests.Session:",
        "    s = requests.Session()",
        '    s.headers.update({"User-Agent": "ohqs-lab/1.0"})',
        "    return s",
        "",
        "",
        "def get(url: str, params: dict[str, str] | None = None) -> dict[str, Any]:",
        "    ensure_evidence()",
        "    r = session().get(url, params=params or {}, timeout=TIMEOUT, allow_redirects=True)",
        "    body = r.text[:200_000]",
        "    snap = {",
        '        "url": r.url,',
        '        "status": r.status_code,',
        '        "headers": dict(r.headers),',
        '        "body_len": len(body),',
        '        "body_sample": body[:4000],',
        "    }",
        '    (EVIDENCE / "last_response.json").write_text(json.dumps(snap, indent=2), encoding="utf-8")',
        "    return snap",
        "",
        "",
        "def post(url: str, data: dict[str, str]) -> dict[str, Any]:",
        "    ensure_evidence()",
        "    r = session().post(url, data=data, timeout=TIMEOUT, allow_redirects=True)",
        "    body = r.text[:200_000]",
        "    snap = {",
        '        "url": r.url,',
        '        "status": r.status_code,',
        '        "headers": dict(r.headers),',
        '        "body_len": len(body),',
        '        "body_sample": body[:4000],',
        "    }",
        '    (EVIDENCE / "last_post.json").write_text(json.dumps(snap, indent=2), encoding="utf-8")',
        "    return snap",
      ),
    },
    {
      path: "src/probes.py",
      content: lines(
        "from __future__ import annotations",
        "import json",
        "import time",
        "from typing import Any",
        "from urllib.parse import urlencode, urlparse, parse_qsl, urlunparse",
        "",
        "from .config import EVIDENCE, ensure_evidence, target_url",
        "from . import http_client",
        "",
        "SQLI_PAYLOADS = [",
        '    "\'",',
        '    "\\"\'\\"",',
        '    "1 AND 1=1",',
        '    "1 AND 1=2",',
        '    "1\' OR \'1\'=\'1",',
        "]",
        "XSS_PAYLOAD = '<svg/onload=console.log(\"ohqs-xss-probe\")>'",
        "CMDI_PAYLOADS = ['; sleep 2', '| sleep 2', '`sleep 2`', '$(sleep 2)']",
        "",
        "",
        "def inject_query(url: str, param: str, value: str) -> str:",
        "    p = urlparse(url)",
        "    q = dict(parse_qsl(p.query, keep_blank_values=True))",
        "    q[param] = value",
        "    return urlunparse(p._replace(query=urlencode(q)))",
        "",
        "",
        "def default_param(url: str) -> str:",
        "    p = urlparse(url)",
        "    q = parse_qsl(p.query, keep_blank_values=True)",
        "    return q[0][0] if q else 'q'",
        "",
        "",
        "def probe_sqli(url: str | None = None) -> dict[str, Any]:",
        "    ensure_evidence()",
        "    base = url or target_url()",
        "    param = default_param(base)",
        "    results = []",
        "    for payload in SQLI_PAYLOADS:",
        "        u = inject_query(base, param, payload)",
        "        snap = http_client.get(u)",
        "        body = snap.get('body_sample') or ''",
        "        err = any(",
        "            s in body.lower()",
        "            for s in ('sql syntax', 'mysql', 'sqlite', 'postgresql', 'odbc', 'ora-')",
        "        )",
        "        results.append({'param': param, 'payload': payload, 'status': snap['status'], 'error_leak': err})",
        "    out = {'target': base, 'param': param, 'results': results}",
        '    (EVIDENCE / "sqli_probe.json").write_text(json.dumps(out, indent=2), encoding="utf-8")',
        "    return out",
        "",
        "",
        "def probe_xss(url: str | None = None) -> dict[str, Any]:",
        "    ensure_evidence()",
        "    base = url or target_url()",
        "    param = default_param(base)",
        "    u = inject_query(base, param, XSS_PAYLOAD)",
        "    snap = http_client.get(u)",
        "    body = snap.get('body_sample') or ''",
        "    reflected = XSS_PAYLOAD in body or 'ohqs-xss-probe' in body",
        "    out = {'target': base, 'param': param, 'reflected': reflected, 'status': snap['status']}",
        '    (EVIDENCE / "xss_probe.json").write_text(json.dumps(out, indent=2), encoding="utf-8")',
        "    return out",
        "",
        "",
        "def probe_cmdi(url: str | None = None) -> dict[str, Any]:",
        "    ensure_evidence()",
        "    base = url or target_url()",
        "    param = default_param(base)",
        "    results = []",
        "    for payload in CMDI_PAYLOADS:",
        "        u = inject_query(base, param, payload)",
        "        t0 = time.time()",
        "        snap = http_client.get(u)",
        "        elapsed = time.time() - t0",
        "        timed = elapsed >= 1.8 and 'sleep' in payload",
        "        results.append({'payload': payload, 'elapsed_s': round(elapsed, 2), 'timed': timed, 'status': snap['status']})",
        "    out = {'target': base, 'param': param, 'results': results}",
        '    (EVIDENCE / "cmdi_probe.json").write_text(json.dumps(out, indent=2), encoding="utf-8")',
        "    return out",
        "",
        "",
        "def probe_secrets_on_disk(root: str = '.') -> dict[str, Any]:",
        "    import re",
        "    from pathlib import Path",
        "",
        "    pat = re.compile(r'(?i)(api[_-]?key|password|secret|authorization)\\s*[:=]\\s*\\S+')",
        "    hits = []",
        "    for p in Path(root).rglob('*'):",
        "        if not p.is_file() or p.suffix in {'.png', '.jpg', '.zip'}:",
        "            continue",
        "        try:",
        "            text = p.read_text(encoding='utf-8', errors='ignore')",
        "        except OSError:",
        "            continue",
        "        for i, line in enumerate(text.splitlines(), 1):",
        "            if pat.search(line):",
        "                hits.append({'file': str(p), 'line': i})",
        "    out = {'hits': hits[:200]}",
        '    (EVIDENCE / "secret_scan.json").write_text(json.dumps(out, indent=2), encoding="utf-8")',
        "    return out",
      ),
    },
    {
      path: "src/recon.py",
      content: lines(
        "from __future__ import annotations",
        "import json",
        "",
        "from .config import EVIDENCE, ensure_evidence, target_url",
        "from . import http_client",
        "",
        "",
        "def run(url: str | None = None) -> dict:",
        "    ensure_evidence()",
        "    u = url or target_url()",
        "    snap = http_client.get(u)",
        "    headers = {k.lower(): v for k, v in (snap.get('headers') or {}).items()}",
        "    expected = [",
        '        "content-security-policy",',
        '        "strict-transport-security",',
        '        "x-content-type-options",',
        '        "x-frame-options",',
        "    ]",
        "    missing = [h for h in expected if h not in headers]",
        "    out = {'target': u, 'status': snap['status'], 'missing_headers': missing, 'headers': headers}",
        '    (EVIDENCE / "recon.json").write_text(json.dumps(out, indent=2), encoding="utf-8")',
        "    return out",
      ),
    },
    {
      path: "src/report.py",
      content: lines(
        "from __future__ import annotations",
        "import json",
        "from pathlib import Path",
        "",
        "from .config import EVIDENCE, ROOT",
        "",
        "",
        "def load_json(name: str) -> dict:",
        "    p = EVIDENCE / name",
        "    if not p.is_file():",
        "        return {}",
        "    return json.loads(p.read_text(encoding='utf-8'))",
        "",
        "",
        "def render_findings() -> str:",
        "    sqli = load_json('sqli_probe.json')",
        "    xss = load_json('xss_probe.json')",
        "    cmdi = load_json('cmdi_probe.json')",
        "    recon = load_json('recon.json')",
        "    lines_out = ['# Automated run summary', '']",
        "    if recon:",
        "        lines_out.append(f\"- Recon status **{recon.get('status')}** — missing headers: {recon.get('missing_headers')}\")",
        "    if sqli:",
        "        leaks = [r for r in sqli.get('results', []) if r.get('error_leak')]",
        "        lines_out.append(f\"- SQLi probes: {len(sqli.get('results', []))} — error leaks: {len(leaks)}\")",
        "    if xss:",
        "        lines_out.append(f\"- XSS reflected: **{xss.get('reflected')}**\")",
        "    if cmdi:",
        "        timed = [r for r in cmdi.get('results', []) if r.get('timed')]",
        "        lines_out.append(f\"- CMDi timed probes: {len(timed)}\")",
        "    md = '\\n'.join(lines_out) + '\\n'",
        "    (ROOT / 'FINDINGS_APPEND.md').write_text(md, encoding='utf-8')",
        "    return md",
      ),
    },
    {
      path: "src/main.py",
      content: pythonMainPy(beef),
    },
    {
      path: "run.sh",
      content: lines(
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        'python3 -m venv .venv 2>/dev/null || true',
        'source .venv/bin/activate 2>/dev/null || true',
        "pip install -q -r requirements.txt",
        'export TARGET_URL="${TARGET_URL:-https://lab.example.invalid}"',
        'python -m src.main "${1:-full}"',
      ),
    },
  ];
}

export function goE2eFiles(_complexity: number, goal: string, _kind: LabKind): LabFile[] {
  const mod = "ohqs.lab/" + slug(goal);
  return [
    { path: "go.mod", content: lines("module " + mod, "", "go 1.22") },
    {
      path: "internal/config/config.go",
      content: lines(
        "package config",
        "",
        "import (",
        '\t"os"',
        '\t"path/filepath"',
        ")",
        "",
        "func Root() string {",
        '\twd, _ := os.Getwd()',
        "\treturn wd",
        "}",
        "",
        "func Evidence(root string) string {",
        '\treturn filepath.Join(root, "evidence")',
        "}",
        "",
        "func Target() string {",
        '\tif v := os.Getenv("TARGET_URL"); v != "" {',
        "\t\treturn v",
        "\t}",
        '\treturn "https://lab.example.invalid"',
        "}",
      ),
    },
    {
      path: "internal/httpclient/client.go",
      content: lines(
        "package httpclient",
        "",
        "import (",
        '\t"io"',
        '\t"net/http"',
        '\t"os"',
        '\t"path/filepath"',
        '\t"time"',
        ")",
        "",
        "func Get(url string, evidenceDir string) (status int, bodySample string, headers map[string]string, err error) {",
        "\t_ = os.MkdirAll(evidenceDir, 0o755)",
        "\tcl := &http.Client{Timeout: 25 * time.Second}",
        "\treq, err := http.NewRequest(http.MethodGet, url, nil)",
        "\tif err != nil {",
        "\t\treturn 0, \"\", nil, err",
        "\t}",
        '\treq.Header.Set("User-Agent", "ohqs-lab/1.0")',
        "\tresp, err := cl.Do(req)",
        "\tif err != nil {",
        "\t\treturn 0, \"\", nil, err",
        "\t}",
        "\tdefer resp.Body.Close()",
        "\tb, _ := io.ReadAll(io.LimitReader(resp.Body, 200000))",
        "\th := map[string]string{}",
        "\tfor k, v := range resp.Header {",
        "\t\tif len(v) > 0 {",
        "\t\t\th[k] = v[0]",
        "\t\t}",
        "\t}",
        "\tsample := string(b)",
        "\tif len(sample) > 4000 {",
        "\t\tsample = sample[:4000]",
        "\t}",
        '\t_ = os.WriteFile(filepath.Join(evidenceDir, "last_response.txt"), []byte(sample), 0o644)',
        "\treturn resp.StatusCode, sample, h, nil",
        "}",
      ),
    },
    {
      path: "internal/probes/probes.go",
      content: lines(
        "package probes",
        "",
        "import (",
        '\t"encoding/json"',
        '\t"net/url"',
        '\t"os"',
        '\t"path/filepath"',
        '\t"strings"',
        '\t"time"',
        "",
        '\t"' + mod + '/internal/config"',
        '\t"' + mod + '/internal/httpclient"',
        ")",
        "",
        "func injectQuery(raw, param, val string) string {",
        "\tu, err := url.Parse(raw)",
        "\tif err != nil {",
        "\t\treturn raw",
        "\t}",
        "\tq := u.Query()",
        "\tq.Set(param, val)",
        "\tu.RawQuery = q.Encode()",
        "\treturn u.String()",
        "}",
        "",
        "func RunAll(root string) error {",
        "\tev := config.Evidence(root)",
        "\tt := config.Target()",
        "\tstatus, body, hdrs, err := httpclient.Get(t, ev)",
        "\tif err != nil {",
        "\t\treturn err",
        "\t}",
        "\trecon := map[string]any{\"target\": t, \"status\": status, \"headers\": hdrs}",
        "\tb, _ := json.MarshalIndent(recon, \"\", \"  \")",
        '\t_ = os.WriteFile(filepath.Join(ev, "recon.json"), b, 0o644)',
        "\tsqliURL := injectQuery(t, \"q\", \"' OR '1'='1\")",
        "\t_, sqBody, _, _ := httpclient.Get(sqliURL, ev)",
        "\tsqliLeak := strings.Contains(strings.ToLower(sqBody), \"sql\")",
        "\txssURL := injectQuery(t, \"q\", \"<svg/onload=ohqs>\")",
        "\t_, xBody, _, _ := httpclient.Get(xssURL, ev)",
        "\treflected := strings.Contains(xBody, \"<svg/onload=ohqs>\")",
        "\tt0 := time.Now()",
        "\tcmdURL := injectQuery(t, \"q\", \";sleep 2\")",
        "\t_, _, _, _ = httpclient.Get(cmdURL, ev)",
        "\ttimed := time.Since(t0) >= 1800*time.Millisecond",
        "\tsummary := map[string]any{",
        "\t\t\"sqli_error_leak\": sqliLeak,",
        "\t\t\"xss_reflected\": reflected,",
        "\t\t\"cmdi_timed\": timed,",
        "\t}",
        "\tb2, _ := json.MarshalIndent(summary, \"\", \"  \")",
        '\t_ = os.WriteFile(filepath.Join(ev, "probes.json"), b2, 0o644)',
        "\treturn nil",
        "}",
      ),
    },
    {
      path: "main.go",
      content: lines(
        "package main",
        "",
        "import (",
        '\t"fmt"',
        '\t"os"',
        "",
        '\t"' + mod + '/internal/config"',
        '\t"' + mod + '/internal/probes"',
        ")",
        "",
        "func main() {",
        "\tif len(os.Args) < 2 {",
        '\t\tfmt.Fprintln(os.Stderr, "usage: go run . <setup|full>")',
        "\t\tos.Exit(2)",
        "\t}",
        "\troot := config.Root()",
        '\tev := config.Evidence(root)',
        "\tswitch os.Args[1] {",
        '\tcase "setup":',
        "\t\t_ = os.MkdirAll(ev, 0o755)",
        '\t\tfmt.Println("target:", config.Target())',
        '\tcase "full":',
        "\t\tif err := probes.RunAll(root); err != nil {",
        "\t\t\tfmt.Fprintln(os.Stderr, err)",
        "\t\t\tos.Exit(1)",
        "\t\t}",
        '\t\tfmt.Println("probes complete — see evidence/")',
        "\tdefault:",
        '\t\tfmt.Fprintln(os.Stderr, "unknown cmd")',
        "\t\tos.Exit(2)",
        "\t}",
        "}",
      ),
    },
  ];
}

export function rustE2eFiles(_complexity: number, _kind: LabKind): LabFile[] {
  return [
    {
      path: "Cargo.toml",
      content: lines(
        "[package]",
        'name = "ohqs_lab"',
        'version = "0.1.0"',
        'edition = "2021"',
        "publish = false",
        "",
        "[dependencies]",
        "reqwest = { version = \"0.12\", default-features = false, features = [\"blocking\", \"json\"] }",
        "serde = { version = \"1\", features = [\"derive\"] }",
        "serde_json = \"1\"",
        "url = \"2\"",
      ),
    },
    {
      path: "src/main.rs",
      content: lines(
        "use std::env;",
        "use std::fs;",
        "use std::path::PathBuf;",
        "use std::time::Instant;",
        "",
        "fn target() -> String {",
        '    env::var("TARGET_URL").unwrap_or_else(|_| "https://lab.example.invalid".into())',
        "}",
        "",
        "fn evidence() -> PathBuf {",
        '    PathBuf::from("evidence")',
        "}",
        "",
        "fn get(client: &reqwest::blocking::Client, url: &str) -> Result<(u16, String), reqwest::Error> {",
        "    let resp = client.get(url).send()?;",
        "    let status = resp.status().as_u16();",
        "    let body = resp.text().unwrap_or_default();",
        "    Ok((status, body))",
        "}",
        "",
        "fn inject_q(base: &str, val: &str) -> String {",
        "    if let Ok(mut u) = url::Url::parse(base) {",
        "        let mut pairs: Vec<(String, String)> = u",
        "            .query_pairs()",
        "            .into_owned()",
        "            .collect();",
        "        if pairs.is_empty() {",
        '            pairs.push(("q".into(), val.into()));',
        "        } else {",
        "            pairs[0].1 = val.into();",
        "        }",
        "        u.query_pairs_mut().clear();",
        "        for (k, v) in pairs {",
        "            u.query_pairs_mut().append_pair(&k, &v);",
        "        }",
        "        return u.to_string();",
        "    }",
        "    base.to_string()",
        "}",
        "",
        "fn main() {",
        "    let cmd = env::args().nth(1).unwrap_or_else(|| \"full\".into());",
        "    fs::create_dir_all(evidence()).expect(\"evidence\");",
        '    if cmd == "setup" {',
        "        println!(\"target: {}\", target());",
        "        return;",
        "    }",
        "    let client = reqwest::blocking::Client::builder()",
        '        .user_agent("ohqs-lab/1.0")',
        "        .build()",
        "        .expect(\"client\");",
        "    let t = target();",
        "    let (status, body) = get(&client, &t).expect(\"recon get\");",
        "    let recon = serde_json::json!({\"target\": t, \"status\": status, \"body_len\": body.len()});",
        '    fs::write(evidence().join("recon.json"), serde_json::to_string_pretty(&recon).unwrap()).unwrap();',
        "    let sqli_url = inject_q(&t, \"' OR '1'='1\");",
        "    let (_, sq_body) = get(&client, &sqli_url).unwrap_or((0, String::new()));",
        "    let sqli_leak = sq_body.to_lowercase().contains(\"sql\");",
        "    let xss_url = inject_q(&t, \"<svg/onload=ohqs>\");",
        "    let (_, x_body) = get(&client, &xss_url).unwrap_or((0, String::new()));",
        "    let xss = x_body.contains(\"<svg/onload=ohqs>\");",
        "    let cmd_url = inject_q(&t, \";sleep 2\");",
        "    let start = Instant::now();",
        "    let _ = get(&client, &cmd_url);",
        "    let timed = start.elapsed().as_millis() >= 1800;",
        "    let probes = serde_json::json!({\"sqli_error_leak\": sqli_leak, \"xss_reflected\": xss, \"cmdi_timed\": timed});",
        '    fs::write(evidence().join("probes.json"), serde_json::to_string_pretty(&probes).unwrap()).unwrap();',
        '    println!("probes complete — see evidence/");',
        "}",
      ),
    },
  ];
}

export function jsE2eFiles(_complexity: number, _kind: LabKind): LabFile[] {
  return [
    {
      path: "package.json",
      content:
        JSON.stringify(
          {
            name: "ohqs-lab",
            version: "0.1.0",
            private: true,
            type: "module",
            description: "OpenHat end-to-end web assessment runner",
            scripts: {
              setup: "node src/index.js setup",
              full: "node src/index.js full",
              start: "node src/index.js full",
            },
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "src/index.js",
      content: lines(
        "import fs from 'node:fs';",
        "import path from 'node:path';",
        "import { fileURLToPath } from 'node:url';",
        "",
        "const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');",
        "const evidence = path.join(root, 'evidence');",
        "",
        "function target() {",
        "  return (process.env.TARGET_URL || 'https://lab.example.invalid').trim();",
        "}",
        "",
        "async function get(url) {",
        "  const res = await fetch(url, {",
        "    redirect: 'follow',",
        "    headers: { 'User-Agent': 'ohqs-lab/1.0' },",
        "  });",
        "  const text = await res.text();",
        "  const sample = text.slice(0, 4000);",
        "  fs.mkdirSync(evidence, { recursive: true });",
        "  fs.writeFileSync(",
        "    path.join(evidence, 'last_response.json'),",
        "    JSON.stringify({ url: res.url, status: res.status, body_sample: sample }, null, 2),",
        "  );",
        "  return { status: res.status, sample };",
        "}",
        "",
        "function injectQuery(base, param, val) {",
        "  const u = new URL(base);",
        "  u.searchParams.set(param, val);",
        "  return u.toString();",
        "}",
        "",
        "async function runFull() {",
        "  const t = target();",
        "  const recon = await get(t);",
        "  fs.writeFileSync(path.join(evidence, 'recon.json'), JSON.stringify({ target: t, ...recon }, null, 2));",
        "  const sqli = await get(injectQuery(t, 'q', \"' OR '1'='1\"));",
        "  const sqliLeak = /sql|mysql|sqlite|postgresql/i.test(sqli.sample);",
        "  const xssPayload = '<svg/onload=ohqs>';",
        "  const xss = await get(injectQuery(t, 'q', xssPayload));",
        "  const reflected = xss.sample.includes(xssPayload);",
        "  const t0 = Date.now();",
        "  await get(injectQuery(t, 'q', ';sleep 2'));",
        "  const timed = Date.now() - t0 >= 1800;",
        "  const probes = { sqli_error_leak: sqliLeak, xss_reflected: reflected, cmdi_timed: timed };",
        "  fs.writeFileSync(path.join(evidence, 'probes.json'), JSON.stringify(probes, null, 2));",
        "  console.log(JSON.stringify(probes, null, 2));",
        "}",
        "",
        "const cmd = process.argv[2] || 'full';",
        "if (cmd === 'setup') {",
        "  fs.mkdirSync(evidence, { recursive: true });",
        "  console.log(JSON.stringify({ target: target() }, null, 2));",
        "} else {",
        "  runFull().catch((e) => {",
        "    console.error(e);",
        "    process.exit(1);",
        "  });",
        "}",
      ),
    },
  ];
}
