package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openhat/quick-start/internal/planner"
)

func Path(exportFlag string) string {
	if strings.HasSuffix(exportFlag, ".sh") {
		return exportFlag
	}
	return filepath.Join(exportFlag, "commands.sh")
}

func Write(exportFlag string, p *planner.Plan, toolBin string) error {
	path := Path(exportFlag)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(Script(p, toolBin)), 0o755); err != nil {
		return err
	}
	if !strings.HasSuffix(exportFlag, ".sh") {
		report := filepath.Join(exportFlag, "FINDINGS.md")
		if err := os.WriteFile(report, []byte(FindingsTemplate(p)), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func FindingsTemplate(p *planner.Plan) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Security assessment — client deliverable\n\n")
	fmt.Fprintf(&b, "**Playbook:** %s\n\n", p.PlaybookTitle)
	fmt.Fprintf(&b, "**Goal:** %s\n\n", p.Goal)
	fmt.Fprintf(&b, "**Scope:** %s\n\n", p.Scope)
	fmt.Fprintf(&b, "**Assessor:** _your firm_\n\n")
	fmt.Fprintf(&b, "**Date:** _YYYY-MM-DD_\n\n")
	fmt.Fprintf(&b, "## Executive summary\n\n")
	fmt.Fprintf(&b, "_2–3 sentences: overall risk, whether the app should remain public, rebuild recommendation._\n\n")
	fmt.Fprintf(&b, "## Findings\n\n")
	fmt.Fprintf(&b, "<!-- Copy one block per confirmed issue. Attach evidence from evidence/ -->\n\n")
	fmt.Fprintf(&b, "### FINDING-001 — _title_\n\n")
	fmt.Fprintf(&b, "- **Severity:** Critical / High / Medium / Low\n")
	fmt.Fprintf(&b, "- **Category:** e.g. Broken access control, XSS, secret exposure\n")
	fmt.Fprintf(&b, "- **Affected:** URL or file path\n")
	fmt.Fprintf(&b, "- **Steps to reproduce:**\n")
	fmt.Fprintf(&b, "  1. _step_\n")
	fmt.Fprintf(&b, "- **Evidence:** `evidence/_file_`\n")
	fmt.Fprintf(&b, "- **Impact:** _what an attacker or user could do_\n")
	fmt.Fprintf(&b, "- **Fix:** _concrete remediation for rebuild_\n\n")
	fmt.Fprintf(&b, "## Coverage (playbook steps)\n\n")
	for _, s := range p.Steps {
		fmt.Fprintf(&b, "- [ ] **%d. %s** — %s\n", s.N, s.Title, s.Purpose)
	}
	fmt.Fprintf(&b, "\n## Recommendation\n\n")
	fmt.Fprintf(&b, "_Rebuild vs patch: tie to severity and cost. Reference ASVS gaps if useful._\n\n")
	fmt.Fprintf(&b, "---\n\n")
	fmt.Fprintf(&b, "_Generated by ohqs. Detection and reporting only — verify every finding manually._\n")
	return b.String()
}

func Script(p *planner.Plan, toolBin string) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Review every command. Only run against the authorized scope.\n")
	b.WriteString("# ohqs does not generate exploits.\n")
	fmt.Fprintf(&b, "#\n# Playbook: %s (%s)\n", p.PlaybookTitle, p.Playbook)
	fmt.Fprintf(&b, "# Goal: %s\n", commentEscape(p.Goal))
	fmt.Fprintf(&b, "# Scope: %s\n", commentEscape(p.Scope))
	b.WriteString("# Copy or run individual commands. Do not blindly execute this whole file.\n")
	if toolBin != "" {
		fmt.Fprintf(&b, "export PATH=%q:\"$PATH\"\n", toolBin)
	}
	b.WriteString("mkdir -p evidence\n")

	for _, s := range p.Steps {
		if len(s.Commands) == 0 {
			fmt.Fprintf(&b, "\n# --- %d. %s ---\n", s.N, s.Title)
			fmt.Fprintf(&b, "# %s\n", commentEscape(s.Purpose))
			if s.How != "" {
				for _, line := range strings.Split(s.How, "\n") {
					fmt.Fprintf(&b, "# %s\n", commentEscape(line))
				}
			}
			continue
		}
		fmt.Fprintf(&b, "\n# --- %d. %s ---\n", s.N, s.Title)
		fmt.Fprintf(&b, "# Purpose: %s\n", commentEscape(s.Purpose))
		if s.How != "" {
			for _, line := range strings.Split(s.How, "\n") {
				if strings.TrimSpace(line) == "" {
					continue
				}
				fmt.Fprintf(&b, "# How: %s\n", commentEscape(line))
			}
		}
		if s.LookFor != "" {
			for _, line := range strings.Split(s.LookFor, "\n") {
				if strings.TrimSpace(line) == "" {
					continue
				}
				fmt.Fprintf(&b, "# Look for: %s\n", commentEscape(line))
			}
		}
		for _, c := range s.Commands {
			fmt.Fprintf(&b, "%s\n", c)
		}
	}
	b.WriteString("\n# done\n")
	return b.String()
}

func commentEscape(s string) string {
	return strings.ReplaceAll(s, "\n", " ")
}
